apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline-secure-kube
spec:
  params:
    - name: pipeline-pvc
      description: the pipeline pvc name
    - name: repository
      description: the git repo
    - name: branch
      description: the branch for the git repo
  tasks:
    - name: pipeline-clone-task
      taskRef:
        name: clone-repo-task
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: repository
          value: $(params.repository)
        - name: branch
          value: $(params.branch)