---
version: '2'
messages:
  $i18n: locales.yml
template:
  name:
    $ref: "#/messages/template.name"
  description:
    $ref: "#/messages/template.description"
  header: '![](toolchain.svg?localize)'
  icon: secure-lock-kubernetes.svg
  required:
    - build
    - app-repo
    - pipeline-repo
    - tekton-catalog-repo
  info:
    git url: >
      "[" + $env.repository + "]" +
        "(" + $env.repository + ")"
    git branch: >
      "[" + $env.branch + "]" +
        "(" + $env.repository +
          "/tree/" + $env.branch + ")"
toolchain:
  name: 'compliance-ci-toolchain-{{timestamp}}'
  template:
    getting_started:
      $ref: "#/messages/template.gettingStarted"
services:
  app-repo:
    service_id: githubpublic
    parameters:
      repo_name: 'hello-containers-{{timestamp}}'
      repo_url: >
        $env.type === 'link' ?
          $env.app_repo : 'https://github.com/open-toolchain/hello-containers'
      source_repo_url: >
        $env.type === 'fork' || $env.type === 'clone' ?
          $env.app_repo : 'https://github.com/open-toolchain/hello-containers'
      type: $env.type || 'clone'
      has_issues: false
      enable_traceability: false
      legal: true
  pipeline-repo:
    service_id: githubpublic
    parameters:
      repo_name: 'testsecure-{{timestamp}}'
      repo_url: >
        $env.type === 'link' ?
          $env.app_repo : 'https://github.com/huayuenh/testsecure'
      source_repo_url: >
        $env.type === 'fork' || $env.type === 'clone' ?
          $env.app_repo : 'https://github.com/huayuenh/testsecure'
      type: $env.type || 'link'
      has_issues: false
      enable_traceability: false
      legal: true
  tekton-catalog-repo:
    service_id: githubpublic
    parameters:
      repo_name: 'tekton-catalog-{{timestamp}}'
      repo_url: >
        $env.type === 'link' ?
          $env.app_repo : 'https://github.com/open-toolchain/tekton-catalog'
      source_repo_url: >
        $env.type === 'fork' || $env.type === 'clone' ?
          $env.app_repo : 'https://github.com/open-toolchain/tekton-catalog'
      type: $env.type || 'link'
      has_issues: false
      enable_traceability: false
      legal: true
  build:
    service_id: pipeline
    parameters:
      services:
        - app-repo
        - pipeline-repo
        - tekton-catalog-repo
      name: '{{services.app-repo.parameters.repo_name}}'
      ui-pipeline: true
      type: tekton
      configuration:
        content:
          $text: pipeline_tekton.yml
        env:
          PIPELINE_REPO: pipeline-repo
          APP_REPO: app-repo
          IMAGE_URL: 'us.icr.io/{{form.pipeline.parameters.registry-namespace}}/{{form.pipeline.parameters.app-name}}'
          APP_NAME: '{{form.pipeline.parameters.app-name}}'
          REGISTRY_REGION_ID: '{{form.pipeline.parameters.registry-region}}'
          REGISTRY_NAMESPACE: '{{form.pipeline.parameters.registry-namespace}}'
          API_KEY: '{{form.pipeline.parameters.api-key}}'
          DEV_REGION_ID: '{{form.pipeline.parameters.dev-region}}'
          DEV_RESOURCE_GROUP: '{{form.pipeline.parameters.dev-resource-group}}'
          DEV_CLUSTER_NAME: '{{form.pipeline.parameters.dev-cluster-name}}'
          DEV_CLUSTER_NAMESPACE: '{{form.pipeline.parameters.dev-cluster-namespace}}'
          APP_REPO_FULL: 'https://github.ibm.com/{{form.app-repo.parameters.owner_id}}/{{form.app-repo.parameters.repo_name}}'
          TEKTON_CATALOG_REPO: tekton-catalog-repo
        execute: false
  webide:
    service_id: orion
form:
  pipeline:
    parameters:
      app-name: '{{services.app-repo.parameters.repo_name}}'
      dev-cluster-namespace: default
      build-cluster-namespace: build
    schema:
      $ref: deploy.json
